homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Indiana/Indianapolis
  # Customization file
  customize: !include includes/customize.yaml
  packages: 
    pack_1: !include packages/recycle_trash.yaml
    pack_2: !include packages/nest_thermostat.yaml
    #pack_3: !include packages/alarm_clock.yaml
    pack_4: !include packages/homeassistant.yaml
    pack_5: !include packages/traffic_cam.yaml
    pack_6: !include packages/cameras.yaml
## Enables the frontend
frontend:

# Show links to resources in log and frontend
introduction:

#https://www.home-assistant.io/components/calendar.google/
google:
  client_id: !secret google_ID_CAL
  client_secret: !secret google_secret_CAL
  
calendar:
  - platform: caldav
    username: !secret google_username
    password: !secret google_Password
    url: !secret google_CAL_URL

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  cors_allowed_origins:
    - http://192.168.1.85:7080
# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Might not need
ios:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Purge Database Interval
recorder:
  purge_interval: 2
  purge_keep_days: 14

# Enables a map showing the location of tracked devices
map:



# Track the sun
sun:

# Weather prediction

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

# Cloud
cloud:
websocket_api:
api:
system_log:

octoprint:
  host: 192.168.1.119
  api_key: octopi_api
  bed: true
  number_of_tools: 2

zwave:
  usb_path: /dev/ttyUSB0

############
# Additional Zones
############
zone:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  icon: mdi:server-network
  radius: 250

zone 2:
  name: Noblesville Middle School
  latitude: !secret MD_latitude
  longitude: !secret MD_longitude
  icon: mdi:hospital-building
  radius: 250

zone 3:
  name: Noblesville School
  latitude: !secret ELE_latitude
  longitude: !secret ELE_longitude
  icon: mdi:home
  radius: 150

media_player: !include includes/media_players.yaml
ifttt: !include includes/ifttt.yaml
binary_sensor: !include includes/binary_sensor.yaml
weblink: !include includes/weblinks.yaml
panel_iframe: !include includes/panel_iframes.yaml
android_ip_webcam: !include includes/android_ip_webcams.yaml
camera: !include includes/cameras.yaml
sensor: !include includes/sensors.yaml
group: !include includes/groups.yaml
automation: !include includes/automations.yaml
script: !include includes/scripts.yaml
device_tracker: !include includes/device_trackers.yaml
panel_custom: !include includes/panel_custom.yaml
# View all events in a logbook
logbook: !include includes/logbook.yaml
#image_processing: !include includes/image_processing.yaml
