###############################################################################
#   @author         :   Trent Stanton
#   @date           :   5/04/2018
#   @package        :   
#   @description    :   Broadlink RM2 Pro Plus & Ceiling Fan Control
#   @url            :   https://community.home-assistant.io/t/ac-split-system-integration-via-harmony-remote/21248
###############################################################################
group:
  bedroomfan:
    name: Bedroom Fan
    control: hidden
    entities:
      - input_select.fan_operation_mode
      - input_number.fan_speed

switch:
  - platform: broadlink
    host: !secret broadlink_rm2_pro_plus
    mac: '34:EA:34:43:31:7D'
    friendly_name: 'Bedroom Remote'
    timeout: 15
#    type: rm2_pro_plus
    switches:
      fanpoweroff:
        friendly_name: "fanpoweroff"
        command_on: 'slU0AA0NGg0aDRoNGhoNGg0aDRsNDRoNGg0aDRoNGg0aDRoNGg0aGg0aDRoNGg0aDRoNGg0AAWEAAAAA'
        command_off: 'slU0AA0NGg0aDRoNGhoNGg0aDRsNDRoNGg0aDRoNGg0aDRoNGg0aGg0aDRoNGg0aDRoNGg0AAWEAAAAA'
      forward_1:
        friendly_name: "forward_1"
        command_on: 'sg40AA0aDRoNGg0bDRoNGw0aDRoNDhkOGg4aDRoOGQ4ZDRobDQ0aGg0aDRoNGw0aDRsMGg0AAWIAAAAA'
        command_off: 'sg40AA0aDRoNGg0bDRoNGw0aDRoNDhkOGg4aDRoOGQ4ZDRobDQ0aGg0aDRoNGw0aDRsMGg0AAWIAAAAA'
      forward_2:
        friendly_name: "forward_2"
        command_on: 'sgc0AAwbDBsMGwwbDBsMGwwbDBsMDhkOGQ4ZDhkOGQ4ZGwwOGQ4ZGwwbDBsMGwwaDRsMGwwAAWMAAAAA'
        command_off: 'sgc0AAwbDBsMGwwbDBsMGwwbDBsMDhkOGQ4ZDhkOGQ4ZGwwOGQ4ZGwwbDBsMGwwaDRsMGwwAAWMAAAAA'
      forward_3:
        friendly_name: "forward_3"
        command_on: 'sgA4AQwaCxsLGgwaDBoMGgwaCxsLDRkNGQ0ZDRgOGA4YGwsaDA0ZGgsbCxsLGgwaDBoMGgwAAVYLGwsaDBoMGgwaCxsLGwsaDA0ZDRkNGA4YDhgOGBoMGgwNGBsLGgwaDBoMGgwaCxsLAAFiDBoLGgwaDBoMGgsbCxsLGwsNGQ0ZDRkNGQ0YDRkaDBoMDRkaCxsLGgwaDBoMGgsbCwABYgwaCxsLGgwaDBoMGgsbCxsLDhgNGQ0YDhgOGQ0ZGQwbCw0ZGgwaCxoMGgwaDBoMGgwAAWEMGgsbCxoMGgwaDBoMGgsbCw4YDRkNGQ0ZDRkNGBsLGgwNGRoLGwwaCxoMGgwaDBoMAAFSDBoMGgsbCxoMGgwaDBoMGgsNGQ4YDRkNGQ0ZDRkaCxsLDRkaDBoMGgsbDBkMGgwaDAAF3A=='
        command_off: 'sgA4AQwaCxsLGgwaDBoMGgwaCxsLDRkNGQ0ZDRgOGA4YGwsaDA0ZGgsbCxsLGgwaDBoMGgwAAVYLGwsaDBoMGgwaCxsLGwsaDA0ZDRkNGA4YDhgOGBoMGgwNGBsLGgwaDBoMGgwaCxsLAAFiDBoLGgwaDBoMGgsbCxsLGwsNGQ0ZDRkNGQ0YDRkaDBoMDRkaCxsLGgwaDBoMGgsbCwABYgwaCxsLGgwaDBoMGgsbCxsLDhgNGQ0YDhgOGQ0ZGQwbCw0ZGgwaCxoMGgwaDBoMGgwAAWEMGgsbCxoMGgwaDBoMGgsbCw4YDRkNGQ0ZDRkNGBsLGgwNGRoLGwwaCxoMGgwaDBoMAAFSDBoMGgsbCxoMGgwaDBoMGgsNGQ4YDRkNGQ0ZDRkaCxsLDRkaDBoMGgsbDBkMGgwaDAAF3A=='
      forward_4:
        friendly_name: "forward_4"
        command_on: 'sgA4AQwaDBoMGgwaCxsLGgwaDBoMDRkNGQ0YDhgOGBoMDRkNGA4YGgwaDBoMGgwaDBoLGwsAAVYMGgwaCxsLGgwaDBoMGgwaCw4YDRkOGA4YDRkaDA0YDhgOGBoMGgwaCxsLGwsaDBoMAAFhDBoMGgwaDBoLGwsbCxoMGgwNGQ0ZDRgOGA4YGgwNGQ0YDhgaDBoMGgwaDBoLGwsaDAABUwsaDBoMGgwaDBoLGwsaDBoMDRkNGQ0ZDRgOGBoMDhgNGQ0YGwsaDBoMGgwaCxsLGgwAAVQLGgwaDBsLGgwaDBoLGwsaDA0ZDRkNGQ0ZDRgaDA0ZDRkNGRoLGwsaDBoMGgwaDBoLAAFUDBoLGwsaDBoMGwsaDBoLGwwMGQ0ZDRkNGQ0ZGgsNGQ0ZDhgaDBoLGwsaDBoMGgwaDAAF3A=='
        command_off: 'sgA4AQwaDBoMGgwaCxsLGgwaDBoMDRkNGQ0YDhgOGBoMDRkNGA4YGgwaDBoMGgwaDBoLGwsAAVYMGgwaCxsLGgwaDBoMGgwaCw4YDRkOGA4YDRkaDA0YDhgOGBoMGgwaCxsLGwsaDBoMAAFhDBoMGgwaDBoLGwsbCxoMGgwNGQ0ZDRgOGA4YGgwNGQ0YDhgaDBoMGgwaDBoLGwsaDAABUwsaDBoMGgwaDBoLGwsaDBoMDRkNGQ0ZDRgOGBoMDhgNGQ0YGwsaDBoMGgwaCxsLGgwAAVQLGgwaDBsLGgwaDBoLGwsaDA0ZDRkNGQ0ZDRgaDA0ZDRkNGRoLGwsaDBoMGgwaDBoLAAFUDBoLGwsaDBoMGwsaDBoLGwwMGQ0ZDRkNGQ0ZGgsNGQ0ZDhgaDBoLGwsaDBoMGgwaDAAF3A=='
      forward_5:
        friendly_name: "forward_5"
        command_on: 'sgA4AQsbCxoMGgwaDBoLGwsbCxsLDRkNGQ0ZDRgOGBoMDRkaCw4YGwsaDBoMGgsbCxoMGgwAAVYMGgwaDBoLGgwaDBoMGwsaCw4YDhgNGQ0ZDRkaDA0YGwsNGRoLGwsaDBoMGgwaDBoMAAFhDBoMGgsbCxoMGgwaDBoMGgsOGA4YDRkNGQ0ZGgsNGRoMDRkaCxsLGwsaDBoMGgwaDAABYQwaCxsLGwsaDBoMGgwaCxsLDRkNGQ0ZDRkNGRoMDBkaDA0ZGgwZDBsLGwsaDBoMGgsAAVMMGgsbCxsLGgwaDBoMGgsbCw0ZDRkNGQ0ZDRkZDA0ZGgwNGRoLGwsaDBoMGgwaDBoLAAFVDBoMGgsaDBsLGwsaDBoMGgsOGA4YDhgNGQ0ZGgwNGBoMDRkaDBkMGwsbCxoMGgwaDAAF3A=='
        command_off: 'sgA4AQsbCxoMGgwaDBoLGwsbCxsLDRkNGQ0ZDRgOGBoMDRkaCw4YGwsaDBoMGgsbCxoMGgwAAVYMGgwaDBoLGgwaDBoMGwsaCw4YDhgNGQ0ZDRkaDA0YGwsNGRoLGwsaDBoMGgwaDBoMAAFhDBoMGgsbCxoMGgwaDBoMGgsOGA4YDRkNGQ0ZGgsNGRoMDRkaCxsLGwsaDBoMGgwaDAABYQwaCxsLGwsaDBoMGgwaCxsLDRkNGQ0ZDRkNGRoMDBkaDA0ZGgwZDBsLGwsaDBoMGgsAAVMMGgsbCxsLGgwaDBoMGgsbCw0ZDRkNGQ0ZDRkZDA0ZGgwNGRoLGwsaDBoMGgwaDBoLAAFVDBoMGgsaDBsLGwsaDBoMGgsOGA4YDhgNGQ0ZGgwNGBoMDRkaDBkMGwsbCxoMGgwaDAAF3A=='
      forward_6:
        friendly_name: "forward_6"
        command_on: 'siI0AAwbDRoNGg0aDRsMGw0aDRoMDhoOGQ4aDhoOGhoMGw0NGg4ZGw0aDRoNGg0bDBsNGg0AAWIAAAAA'
        command_off: 'siI0AAwbDRoNGg0aDRsMGw0aDRoMDhoOGQ4aDhoOGhoMGw0NGg4ZGw0aDRoNGg0bDBsNGg0AAWIAAAAA'
      reverse_1:
        friendly_name: "reverse_1"
        command_on: 'sgo0AA0aDRsNGwwbDBoNGw0bDBsNDhoaDA0aDhoOGQ4ZDRoaDA4aGwwbDBoNGgwbDBsNGw0AAV8AAAAA'
        command_off: 'sgo0AA0aDRsNGwwbDBoNGw0bDBsNDhoaDA0aDhoOGQ4ZDRoaDA4aGwwbDBoNGgwbDBsNGw0AAV8AAAAA'
      reverse_2:
        friendly_name: "reverse_2"
        command_on: 'sgc0AAwbDBsMGw0bDRsMGw0aDRoNDhoaDQ0ZDRoOGQ4aGw0OGQ4ZGgwbDRsNGw0bDBoNGg0AAWMAAAAA'
        command_off: 'sgc0AAwbDBsMGw0bDRsMGw0aDRoNDhoaDQ0ZDRoOGQ4aGw0OGQ4ZGgwbDRsNGw0bDBoNGg0AAWMAAAAA'
      reverse_3:
        friendly_name: "reverse_3"
        command_on: 'sgo0AAwaDRsNGw0bDRsMGg0aDBsNDhoaDA0ZDhkOGQ4aGwwbDA0ZGw0bDRsNGg0aDRoMGw0AAWMAAAAA'
        command_off: 'sgo0AAwaDRsNGw0bDRsMGg0aDBsNDhoaDA0ZDhkOGQ4aGwwbDA0ZGw0bDRsNGg0aDRoMGw0AAWMAAAAA'
      reverse_4:
        friendly_name: "reverse_4"
        command_on: 'sQc0AAwbDBsMGwwbDBwLHAwcDBsMDxgbDA4ZDhkPGRsMDhkOGQ8ZHAscDBsLGwwbDBwMHAwAAWMAAAAA'
        command_off: 'sQc0AAwbDBsMGwwbDBwLHAwcDBsMDxgbDA4ZDhkPGRsMDhkOGQ8ZHAscDBsLGwwbDBwMHAwAAWMAAAAA'
      reverse_5:
        friendly_name: "reverse_5"
        command_on: 'sgg0AAwbDBsMGwwbDBsNGg0bDBsMDhoaDQ4ZDhoOGRsMDhkaDQ0aGg0aDRsMGwwaDRsMGwwAAWMAAAAA'
        command_off: 'sgg0AAwbDBsMGwwbDBsNGg0bDBsMDhoaDQ4ZDhoOGRsMDhkaDQ0aGg0aDRsMGwwaDRsMGwwAAWMAAAAA'
      reverse_6:
        friendly_name: "reverse_6"
        command_on: 'sg00AAwbDBsMGg0bDBoNGgwbDBsMDhoaDQ0aDhkOGhoNGwwOGQ4ZGgwbDRsMGwwbDBsMGg0AAWAAAAAA'
        command_off: 'sg00AAwbDBsMGg0bDBoNGgwbDBsMDhoaDQ0aDhkOGhoNGwwOGQ4ZGgwbDRsMGwwbDBsMGg0AAWAAAAAA'

input_number:
  fan_speed:
    name: Set Speed
    min: 1
    max: 6
    step: 1
    initial: 2
    mode: slider

input_select:
  fan_operation_mode:
    name: Operating Mode
    options:
      - Forward
      - Reverse
      - Power Off
    initial: Power Off
    icon: mdi:settings

sensor:
  - platform: template
    sensors:
      fan_operation_mode_temp:
        friendly_name: "Fan Operation Mode Template"
        value_template: >-
          {% if is_state('input_select.fan_operation_mode', 'Forward') %}
            forward
          {% elif is_state('input_select.fan_operation_mode', 'Reverse') %}
            reverse
          {% else %}
            poweroff
          {% endif %}
      fan_setting:
        friendly_name: 'Current Fan Setting'
        value_template: 'switch.{{ states.sensor.fan_operation_mode_temp.state }}_{{ states.input_number.fan_speed.state | int }}'
# Value Example 'forward_1' or 'reverse_1'

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: Fan Start
    hide_entity: True
    trigger:
    - platform: state
      entity_id: sensor.fan_setting
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.fan_operation_mode_temp
          state: 'forward'
        - condition: state
          entity_id: sensor.fan_operation_mode_temp
          state: 'reverse'
    action:
    - service: switch.turn_on
      data_template:
        entity_id: "{{ states.sensor.fan_setting.state }}"

  - alias: Fan Stop
    hide_entity: True
    trigger:
    - platform: state
      entity_id: sensor.fan_operation_mode_temp
      to: 'poweroff'
    action:
    - service: switch.turn_on
      entity_id: switch.fanpoweroff