homeassistant:
  customize:

    group.home__family:
      order: 1

    device_tracker.suresh_suresh:
      friendly_name: Suresh
      entity_picture: /local/suresh.jpg
    device_tracker.mallika_mallika:
      friendly_name: Mallika
      entity_picture: /local/mallika.jpg
    device_tracker.srinika_srinika:
      friendly_name: Srinika
      entity_picture: /local/srinika.jpg
    device_tracker.hasika_hasika:
      friendly_name: Hasika
      entity_picture: /local/hasika.jpg
    device_tracker.ipad_ipad:
      hidden: true

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True

group:
  Home & Family:
    control: hidden
    entities:
      - device_tracker.suresh_suresh
      - device_tracker.mallika_mallika
      - device_tracker.srinika_srinika
      - device_tracker.hasika_hasika
      - alarm_control_panel.simplisafe
      - input_boolean.emergency_mode
      - input_boolean.home_mode_away