###############################################################################
#   @author         :   Trent Stanton
#   @date           :   9/04/2018
#   @package        :   
#   @description    :   Security Sensors
#   @url            :   
###############################################################################
homeassistant:
  customize:
    sensor.door_count:
      friendly_name: Open Door Count
      icon: mdi:window-open
    sensor.window_count:
      friendly_name: Open Window Count
      icon: mdi:door-open
    binary_sensor.door_window_sensor_158d000186f0ec:
      friendly_name: Back Door Sensor
      device_class: door
    binary_sensor.door_window_sensor_158d00019f3211:
      friendly_name: Front Door Sensor
      device_class: door
    binary_sensor.door_window_sensor_158d0001d7acfc:
      friendly_name: Bedroom Window Sensor
      device_class: window
    binary_sensor.door_window_sensor_158d0001e037dc:
      friendly_name: Living Room Window Sensor 1
      device_class: window
    binary_sensor.door_window_sensor_158d00019fbe38:
      friendly_name: Living Room Window Sensor 2
      device_class: window
    binary_sensor.door_window_sensor_158d0001a4a872:
      friendly_name: Living Room Window Sensor 3
      device_class: window

group:
  doorandwindowsensors:
    name: Door and Window Sensors
    control: hidden
    entities:
      - sensor.door_count
      - sensor.window_count
      - binary_sensor.door_window_sensor_158d00019f3211
      - binary_sensor.door_window_sensor_158d000186f0ec
      - binary_sensor.door_window_sensor_158d0001d7acfc
      - binary_sensor.door_window_sensor_158d0001e037dc
      - binary_sensor.door_window_sensor_158d00019fbe38
      - binary_sensor.door_window_sensor_158d0001a4a872

sensor:
  - platform: template
    sensors:
      door_count:
        value_template: >-
          {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'door') | list | count }}
      window_count:
        value_template: >-
          {{ states.binary_sensor | selectattr('state', 'eq', 'on') | selectattr('attributes.device_class', 'eq', 'window') | list | count }}