############################################################
#
# Home Assistant Lights
#
############################################################

############
# Yeelight
############
- platform: yeelight
  devices:
    !secret study_desk_lamp_light_ip:
      name: Study Desk Lamp
      transition: 1000
    !secret trent_bedside_light_ip:
      name: Trent Bedside
    !secret rachel_bedside_light_ip:
      name: Rachel Bedside
