###############################################################################
#   @author         :   
#   @date           :   10/02/2018
#   @package        :   Alarm System
#   @description    :   MQTT Alarm System with Alarm from Xiaomi Gateway when alarm panel is Armed and triggered.
#   @url            :   
###############################################################################
group:
  security:
    name: Security
    control: hidden
    entities:
      - lock.front_door
      - alarm_control_panel.ha_alarm
      - binary_sensor.motion
      - binary_sensor.motion_sensor_158d000165627b

# MQTT Control Panel
alarm_control_panel:
  - platform: manual_mqtt
    state_topic: "home/alarm"
    command_topic: "home/alarm/set"
    code: !secret alarm_code

###############################################################################
#                               Automations
###############################################################################
automation:
# Trigger alarm while armed away
  - alias: 'Trigger alarm while armed away'
    trigger:
    - platform: state
      entity_id: binary_sensor.motion
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00015b5ae2
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000165627b
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00016be35b
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d000186f0ec
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00019f3211
      to: 'on'
    condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
    action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
  
# Start Police Siren on Alarm Trigger via Xiaomi Gateway
  
  - alias: Start Police Siren on Alarm Trigger
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
    action:
    - service: xiaomi.play_ringtone
      data:
        gw_mac: !secret xiaomimac
        ringtone_id: 10001
        ringtone_vol: 100
    - service: light.turn_on
      entity_id: group.all_lights
    - service: notify.trent
      data:
        message: "Police Siren has been triggered at home"
        data:
          actions:
          - action: open
            title: Open Home Assistant
            url: !secret base_url
  
# Stop Police Siren via Xiaomi Gateway
  
  - alias: Stop Police Siren
    trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      from: 'triggered'
    action:
      service: xiaomi.stop_ringtone
      data:
        gw_mac: !secret xiaomimac  