###############################################################################
#   @author         :   Trent Stanton
#   @date           :   24/02/2018
#   @package        :   Chromecast Radio
#   @description    :   Casts Web Radio stations to Chromecast/Google Home
#   @url            :   
###############################################################################

group:
  radio:
    name: Radio
    control: hidden
    entities:
      - input_select.radio_player
      - input_select.radio_station
      - input_number.google_volume

input_number:
  google_volume:
    name: Volume
    initial: 3
    min: 0
    max: 10
    step: 0.5
    mode: slider
    icon: mdi:volume-medium

input_select:
  radio_station:
    name: Radio Station
    options:
      - Triple J
      - Double J
      - Nova 100
      - SmoothFM
      - SBS Chill
      - "None"
    initial: "None"
    icon: mdi:radio
  radio_player:
    name: Radio Player
    options:
      - Living Room Home
      - Living Room Chromecast
      - Bed Room Chromecast
      - Outside Chromecast Audio
      - "None"
    initial: "None"
    icon: mdi:cast

sensor:

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: STOP Streaming Radio on CHROMECAST
    trigger:
    - platform: state
      entity_id: input_select.radio_station
      to: "None"
    action:
    - service: media_player.turn_off
      data_template:
        entity_id: >
            {% if is_state("input_select.radio_player", "Living Room Home") %}
              media_player.living_room_home
            {%-elif is_state("input_select.radio_player", "Living Room Chromecast") %}
              media_player.living_room
            {%-elif is_state("input_select.radio_player", "Bed Room Home") %}
              media_player.bedroom_speaker
            {%-elif is_state("input_select.radio_player", "Outside Chromecast Audio") %}
              media_player.outside
            {% else %}
              "None"
            {% endif %}
  
  - alias: START Streaming Radio on CHROMECAST
    trigger:
    - platform: state
      entity_id: input_select.radio_station
    action:
    - service: media_player.play_media
      data_template:
        entity_id: >
          {% if is_state("input_select.radio_player", "Living Room Home") %}
            media_player.living_room_home
          {%-elif is_state("input_select.radio_player", "Living Room Chromecast") %}
            media_player.living_room
          {%-elif is_state("input_select.radio_player", "Bed Room Home") %}
            media_player.bedroom_speaker
          {%-elif is_state("input_select.radio_player", "Outside Chromecast Audio") %}
            media_player.outside
          {% else %}
            "None"
          {% endif %}
        media_content_id: >
          {% if is_state("input_select.radio_station", "Triple J") %}
            http://live-radio01.mediahubaustralia.com/2TJW/aac/Triple J NSW.aac
          {%-elif is_state("input_select.radio_station", "Double J") %}
            http://live-radio01.mediahubaustralia.com/DJDW/aac/Double J NSW.aac
          {%-elif is_state("input_select.radio_station", "Nova 100") %}
            http://streaming.novaentertainment.com.au/nova100
          {%-elif is_state("input_select.radio_station", "SmoothFM") %}
            http://streaming.novaentertainment.com.au/smooth915
          {%-elif is_state("input_select.radio_station", "SBS Chill") %}
            http://shoutcast.sbs.com.au/SBSChill
          {% else %}
            "None"
          {% endif %}
        media_content_type: 'audio/mp4'

  - alias: change volume google
    trigger:
    - platform: state
      entity_id: input_number.google_volume
    condition:
    - condition: template
      value_template: "{{ states.input_select.radio_player.state != 'OFF' }}"
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.radio_player", "Living Room Home") %}
            media_player.living_room_home
          {% elif is_state("input_select.radio_player", "Living Room Chromecast") %}
            media_player.living_room
          {% elif is_state("input_select.radio_player", "Bed Room Home") %}
            media_player.bedroom_speaker
          {%-elif is_state("input_select.radio_player", "Outside Chromecast Audio") %}
            media_player.outside
          {% else %}
            "None"
          {% endif %}
        volume_level: "{{ states.input_number.google_volume.state | float / 10 }}"  