###############################################################################
#
#                                DEVICE TRACKERS
#
###############################################################################
device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: root
    password: admin
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False
  - platform: ddwrt
    host: 192.168.1.5
    username: root
    password: admin
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False
  - platform: ddwrt
    host: 192.168.1.2
    username: root
    password: admin
    new_device_defaults:
      track_new_devices: True
      hide_if_away: False
  - platform: nmap_tracker
    consider_home: 120
    interval_seconds: 10
    hosts: 192.168.1.1/24
  - platform: bluetooth_tracker
    interval_seconds: 20
    consider_home: 120
    request_rssi: true
    track_new_devices: yes
group:
  Allen:
    entities:
      - device_tracker.allens_iphone
      - device_tracker.allens_iphone_2
      - device_tracker.allensiphone
  Allen_Work:
    entities:
      - device_tracker.farmerwork
      - device_tracker.farmerwork_2
  Allens_Car:
    entities:
      - device_tracker.obdii
  Stephanie:
    entities:
      - device_tracker.stephanesiphone
      - device_tracker.stephaniesipad
  Chloe:
    entities:
      - device_tracker.101114
  Sheldon:
    entities:
      - device_tracker.sheldonsiphone
  Kaydee:
    entities:
      - device_tracker.kaydeesipad
  people_status:
  name: People Status
  entities:
    - sensor.allen_status
    - sensor.stephanie_status
    - sensor.chloe_status
    - sensor.sheldon_status_dropdown
    - sensor.kaydee_status
sensor:
  - platform: template
    sensors:
      allen_status:
        value_template: '{{ states.input_select.allen_status_dropdown.state }}'
        friendly_name: 'Allen'
      stephanie_status:
        value_template: '{{ states.input_select.stephanie_status_dropdown.state }}'
        friendly_name: 'Stephanie'
      chloe_status:
        value_template: '{{ states.input_select.chloe_status_dropdown.state }}'
        friendly_name: 'Chloe'
      sheldon_status:
        value_template: '{{ states.input_select.sheldon_status_dropdown.state }}'
        friendly_name: 'Sheldon'
      kaydee_status:
        value_template: '{{ states.input_select.kaydee_status_dropdown.state }}'
        friendly_name: 'Kaydee'
input_select:
  allen_status_dropdown:
    name: Allen
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  stephanie_status_dropdown:
    name: Stephanie
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  chloe_status_dropdown:
    name: Chloe
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  sheldon_status_dropdown:
    name: Sheldon
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
  kaydee_status_dropdown:
    name: Kaydee
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
    initial: Home
automation:
  - alias: Mark person as just arrived
    trigger:
      - platform: state
        entity_id: device_tracker.allens_iphone
        from: 'not_home'
        to: 'home'
      - platform: state
        entity_id: group.stephanie
        from: 'not_home'
        to: 'home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'device_tracker.allens_iphone' %}
              input_select.allen_status_dropdown
            {% else %}
              input_select.stephanie_status_dropdown
            {% endif %}
          option: Just Arrived
 
  - alias: Mark person as home
    trigger:
      - platform: state
        entity_id: input_select.allen_status_dropdown
        to: 'Just Arrived'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.stephanie_status_dropdown
        to: 'Just Arrived'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.allen_status_dropdown
        from: 'Just Left'
        to: 'Just Arrived'
      - platform: state
        entity_id: input_select.stephanie_status_dropdown
        from: 'Just Left'
        to: 'Just Arrived'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.allen_status_dropdown' %}
              input_select.allen_status_dropdown
            {% else %}
              input_select.stephanie_status_dropdown
            {% endif %}
          option: Home
 
  - alias: Mark person as just left
    trigger:
      - platform: state
        entity_id: device_tracker.allens_iphone
        from: 'home'
        to: 'not_home'
      - platform: state
        entity_id: group.stephanie
        from: 'home'
        to: 'not_home'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'device_tracker.allens_iphone' %}
              input_select.allen_status_dropdown
            {% else %}
              input_select.stephanie_status_dropdown
            {% endif %}
          option: Just Left
 
  - alias: Mark person as away
    trigger:
      - platform: state
        entity_id: input_select.allen_status_dropdown
        to: 'Just Left'
        for:
          minutes: 10
      - platform: state
        entity_id: input_select.stephanie_status_dropdown
        to: 'Just Left'
        for:
          minutes: 10
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.allen_status_dropdown' %}
              input_select.phil_status_dropdown
            {% else %}
              input_select.allen_status_dropdown
            {% endif %}
          option: Away
 
  - alias: Mark person as extended away
    trigger:
      - platform: state
        entity_id: input_select.allen_status_dropdown
        to: 'Away'
        for:
          hours: 24
      - platform: state
        entity_id: input_select.stephanie_status_dropdown
        to: 'Away'
        for:
          hours: 24
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id == 'input_select.allen_status_dropdown' %}
              input_select.allen_status_dropdown
            {% else %}
              input_select.stephanie_status_dropdown
            {% endif %}
          option: Extended Away