homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'garegedoors'

      exposed: &exposed
        <<: *customize
        emulated_hue_hidden: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue_hidden: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false
  
    zwave.two_car_garage_door_tilt_sensor:
      friendly_name: 2-Car Garage Door Sensor
      <<: *hidden
    zwave.single_car_garage_door_tilt_sensor:
      friendly_name: 1-Car Garage Door Sensor
      <<: *hidden

    binary_sensor.single_car_garage_door_tilt_sensor_sensor:
      <<: *hidden
      device_class: opening
      friendly_name: Single Car Garage Door
    binary_sensor.two_car_garage_door_tilt_sensor_sensor:
      <<: *hidden
      device_class: opening
      friendly_name: Double Car Garage Door

group:
  Garage Doors:
    entities:
      - binary_sensor.single_car_garage_door_tilt_sensor_sensor
      - binary_sensor.two_car_garage_door_tilt_sensor_sensor
      - sensor.single_car_garage_door_sensor_status
      - sensor.two_car_garage_door_sensor_status
      
sensor:
  - platform: template
    sensors:
      single_car_garage_door_sensor_status:
        friendly_name: Single Car Garage Door Sensor Status
        value_template: >-
          {% if states.binary_sensor.single_car_garage_door_tilt_sensor_sensor.state == 'on' %}
            Open
          {% elif states.binary_sensor.single_car_garage_door_tilt_sensor_sensor.state == 'off' %}
            Closed
          {% else %}
            Unknown
          {% endif %}
        icon_template: >-
          {% set door_status = states.binary_sensor.single_car_garage_door_tilt_sensor_sensor.state |d('unknown') %}
          {% if door_status == 'unknown' %}
            mdi:alert-circle
          {% else %}
            {% if door_status == 'on' %}
              mdi:garage-open
            {% else %}
              mdi:garage
            {% endif %}
          {% endif %}
  
  - platform: template
    sensors:
      two_car_garage_door_sensor_status:
        value_template: >-
          {% if states.binary_sensor.two_car_garage_door_tilt_sensor_sensor.state == 'on' %}
            Open
          {% elif states.binary_sensor.two_car_garage_door_tilt_sensor_sensor.state == 'off' %}
            Closed
          {% else %}
            Unknown
          {% endif %}
        friendly_name: Double Car Garage Door Sensor Status
        icon_template: >-
          {% set door_status = states.binary_sensor.two_car_garage_door_tilt_sensor_sensor.state |d('unknown') %}
          {% if door_status == 'unknown' %}
            mdi:alert-circle
          {% else %}
            {% if door_status == 'on' %}
              mdi:garage-open
            {% else %}
              mdi:garage
            {% endif %}
          {% endif %}

binary_sensor:
  - platform: mqtt
    state_topic: "/garage/motion"
    name: "Garage Motion"
    device_class: motion
    payload_on: 'on'
    payload_off: 'off'
    value_template: "{{ value }}"

automation:

  - alias: Garage Motion Reset
    initial_state: true
    hide_entity: true  
    trigger:
      - platform: state
        entity_id: binary_sensor.garage_motion
        to: 'on'
        from: 'off'
    action:
      - delay: '00:00:30'
      - service: mqtt.publish
        data:
          topic: "/garage/motion"
          payload: 'off'
          retain: false

################################################################################
# Notifies when either of the garage door is opened or closed
# When the garage is opened, it sends an actionable ios notification with an 
# option to close the garage door. This iso actionable notification only occurs 
# when garage door is open and not when it is closed.
###############################################################################
  - alias: Notify Garage Door Status
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: 
      - binary_sensor.two_car_garage_door_tilt_sensor_sensor
      - binary_sensor.single_car_garage_door_tilt_sensor_sensor
    condition:
      - condition: template
        value_template: "{% if trigger.from_state %} True {% else %} False {% endif %}"
    action:
      - service: script.notify_me
        data_template:
          message: >
              {% if trigger.to_state.state | lower == "on" %}
                  {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
              {% elif trigger.to_state.state | lower == "off" %}
                  {{ trigger.to_state.attributes.friendly_name }} is now CLOSED!
              {% endif %}
      - service_template: >
          {% if trigger.to_state.state | lower == "on" %}
            switch.turn_on
          {% else %}
            switch.turn_off
          {% endif%}
        data:
          entity_id: switch.garage_lights
      - service: script.voice_notify
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "on" %}
              Attention! Your {{ trigger.to_state.attributes.friendly_name }} is now OPENED!
            {% elif trigger.to_state.state | lower == "off" %}
              Your {{ trigger.to_state.attributes.friendly_name }} is now CLOSED!
            {% endif %}

################################################################################
#  When I open the garage door
#     if it is dark outside, OR
#     both the garage doors are closed
#       ==> turn the Garage lights ON, and start timer!
################################################################################
  - alias: Garage Lights On When Door is Opened
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.garage_door_sensor_sensor
      to: 'on'
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: '{{states.sun.sun.state == "below_horizon"}}'
        - condition: and
          conditions:
            - condition: template
              value_template: "{{ states.binary_sensor.single_car_garage_door_tilt_sensor_sensor.state == 'off' }}"
            - condition: template
              value_template: "{{ states.binary_sensor.two_car_garage_door_tilt_sensor_sensor.state == 'off' }}"      
    action:
      - service: switch.turn_on
        entity_id: switch.garage_lights
      - service: timer.start
        entity_id: timer.timer_garage

# Notify Entry Door Status
###############################################################################
  - alias: Notify Entry Door Status
    initial_state: true
    hide_entity: true    
    trigger:
      platform: state
      entity_id: 
        - binary_sensor.front_door_sensor_sensor
        - binary_sensor.back_door_sensor_sensor
    condition:
      - condition: template
        value_template: "{% if trigger.from_state %} True {% else %} False {% endif %}"
    action:
      - service: script.voice_notify
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "on" %}
              Your {{ trigger.to_state.attributes.friendly_name.replace('Sensor', '') }} is OPEN,
              {% if states.alarm_control_panel.simplisafe.state == 'armed_home' or states.alarm_control_panel.simplisafe.state == 'armed_away' %}
              But your home security system is ON.
              {% endif %}
            {% elif trigger.to_state.state | lower == "off" %}
              Your {{ trigger.to_state.attributes.friendly_name.replace('Sensor', '') }} is CLOSED!
            {% endif %}
          greeting: 'no'
          only_at_night: >
            {% if states.alarm_control_panel.simplisafe.state == 'armed_home' %}
              no
            {% else %}
              yes
            {% endif %}

# Turn ON and OFF basement ambient lights
###############################################################################
  - alias: Basement Accent Lights ON When Basement Door Opened
    initial_state: true
    hide_entity: true    
    trigger:
      platform: state
      entity_id: binary_sensor.basement_door_sensor_sensor
      to: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.rf_switch_one

  - alias: Basement Accent Lights OFF After 5 minutes
    initial_state: true
    hide_entity: true    
    trigger:
      platform: state
      entity_id: 
        - switch.rf_switch_one
      to: 'on'
      for:
        minutes: 5
    action:
      - service: homeassistant.turn_off
        entity_id: switch.rf_switch_one
