homeassistant:
  customize:

    # Locations
    sensor.suresh_location:
      friendly_name: Suresh is at
      icon: mdi:map-marker
    sensor.mallika_location:
      friendly_name: Mallika is at
      icon: mdi:map-marker
    sensor.srinika_location:
      friendly_name: Srinika is at
      icon: mdi:map-marker
    sensor.hasika_location:
      friendly_name: Hasika is at
      icon: mdi:map-marker

    # Travel Times
    sensor.home2work:
      friendly_name: Home -> Work
      icon: mdi:domain
    sensor.work2home:
      friendly_name: Work -> Home
      icon: mdi:home
    sensor.suresh2home:
      friendly_name: Suresh -> Home
      icon: mdi:home
    sensor.suresh2work:
      friendly_name: Suresh -> Work
      icon: mdi:domain
    sensor.srinika2home:
      friendly_name: Srinika -> Home
      icon: mdi:home
    sensor.hasika2home:
      friendly_name: Hasika -> Home
      icon: mdi:home

    group.where_is_everyone:
      order: 7
    group.travel_time:
      order: 6

group:
  Travel Time:
    entities:
      - sensor.home2work
      - sensor.work2home
      - sensor.suresh2work
      - sensor.suresh2home
      - sensor.srinika2home
      - sensor.hasika2home

  Where is everyone:
    entities:
      - sensor.suresh_location
      - sensor.mallika_location
      - sensor.srinika_location
      - sensor.hasika_location

# Google Calendar
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

# Google Travel Times and Geo Code/Location
sensor:
  - platform: google_travel_time
    name: Home2Work
    api_key: !secret google_travel_time_apikey 
    origin: zone.home
    destination: zone.work
    options:
      mode: driving
  
  - platform: google_travel_time
    name: Work2Home
    api_key: !secret google_travel_time_apikey 
    origin: zone.work
    destination: zone.home
    options:
      mode: driving
  
  - platform: google_travel_time
    name: Suresh2Home
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.suresh_suresh
    destination: zone.home
    options:
      mode: driving

  - platform: google_travel_time
    name: Srinika2Home
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.srinika_srinika
    destination: zone.home
    options:
      mode: driving

  - platform: google_travel_time
    name: Hasika2Home
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.hasika_hasika
    destination: zone.home
    options:
      mode: driving

  - platform: google_travel_time
    name: Suresh2Work
    api_key: !secret google_travel_time_apikey 
    origin: device_tracker.suresh_suresh
    destination: zone.work
    options:
      mode: driving

    #  Address/Location Details
  - platform: google_geocode
    name: Suresh Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.suresh_suresh
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Mallika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.mallika_mallika
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Srinika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.srinika_srinika
    options: formatted_address
    display_zone: hide

  - platform: google_geocode
    name: Hasika Location
    api_key: !secret google_maps_geocoding_api
    origin: device_tracker.hasika_hasika
    options: formatted_address
    display_zone: hide