homeassistant:
  customize:
    group.family:
      order: 1
    group.ios:
      order: 98

    device_tracker.ipad:
      hidden: true
    device_tracker.suresh:
      hidden: true
    device_tracker.mallika:
      hidden: true
    device_tracker.srinika:
      hidden: true
    device_tracker.hasika:
      hidden: true

# Battery Levels
    sensor.suresh_battery_level:
      friendly_name: Suresh's Battery Level
      hidden: true
    sensor.mallika_battery_level:
      friendly_name: Mallika's Battery Level
      hidden: true
    sensor.srinika_battery_level:
      friendly_name: Srinika's Battery Level
      hidden: true
    sensor.hasika_battery_level:
      friendly_name: Hasika's Battery Level
      hidden: true
    sensor.ipad_battery_level:
      friendly_name: iPad's Battery State
      hidden: true      
    sensor.iphone__battery_level:
      friendly_name: iPhone
      hidden: true

    sensor.suresh_battery_state:
      friendly_name: Suresh's Battery State
      hidden: true
    sensor.mallika_battery_state:
      friendly_name: Mallika's Battery State
      hidden: true
    sensor.srinika_battery_state:
      friendly_name: Srinika's Battery State
      hidden: true
    sensor.hasika_battery_state:
      friendly_name: Hasika's Battery State
      hidden: true
    sensor.ipad_battery_state:
      friendly_name: iPad's Battery State
      hidden: true
    sensor.iphone__battery_state:
      friendly_name: iphone
      hidden: true
