###############################################################################
#   @author         :   Mahasri Kalavala
#   @date           :   07/16/2017
#   @package        :   QNAP
#   @description    :   QNAP NAS Package
###############################################################################
homeassistant:
  customize:
    sensor.kalavalanas_cpu_usage:
      friendly_name: CPU Usage
    sensor.kalavalanas_memory_usage:
      friendly_name: Memory Usage
    sensor.kalavalanas_network_up_eth0:
      friendly_name: Network Speed
    sensor.kalavalanas_network_up_eth1:
      friendly_name: Network Speed
    sensor.kalavalanas_status:
      friendly_name: NAS Status
    sensor.kalavalanas_volume_used_datavol1:
      friendly_name: Percent Disk Used
    sensor.kalavalanas_system_temperature:
      friendly_name: System Temperature
    sensor.kalavalanas_cpu_temperature:
      friendly_name: CPU Temperature
    sensor.kalavalanas_drive_smart_status:
      friendly_name: Drive Smart Status
    sensor.kalavalanas_drive_temp:
      friendly_name: Drive Temperature
    sensor.nas_memory_usage_above_80:
      friendly_name: Is Memory Above 80 Percent?
      hidden: true
    sensor.nas_cpu_usage_above_80:
      friendly_name: Is CPU Above 80 Percent?
      hidden: true

    sensor.kalavalanas_smart_status_drive_01:
      friendly_name: Drive 1 Status
    sensor.kalavalanas_smart_status_drive_02:
      friendly_name: Drive 2 Status
    sensor.kalavalanas_smart_status_drive_03:
      friendly_name: Drive 3 Status
    sensor.kalavalanas_smart_status_drive_04:
      friendly_name: Drive 4 Status
    
    sensor.kalavalanas_temperature_drive_01:
      friendly_name: Drive 1 Temperature
    sensor.kalavalanas_temperature_drive_02:
      friendly_name: Drive 2 Temperature
    sensor.kalavalanas_temperature_drive_03:
      friendly_name: Drive 3 Temperature
    sensor.kalavalanas_temperature_drive_04:
      friendly_name: Drive 4 Temperature

group:
  QNAP Drives:
    entities:
      - sensor.kalavalanas_smart_status_drive_01
      - sensor.kalavalanas_smart_status_drive_02
      - sensor.kalavalanas_smart_status_drive_03
      - sensor.kalavalanas_smart_status_drive_04
      - sensor.kalavalanas_temperature_drive_01
      - sensor.kalavalanas_temperature_drive_02
      - sensor.kalavalanas_temperature_drive_03
      - sensor.kalavalanas_temperature_drive_04

  QNAP Server:
    entities:
      - sensor.kalavalanas_status
      - sensor.kalavalanas_cpu_usage
      - sensor.kalavalanas_memory_usage
      - sensor.kalavalanas_network_up_eth0
      - sensor.kalavalanas_network_up_eth1
      - sensor.kalavalanas_volume_used_datavol1
      - sensor.kalavalanas_drive_smart_status
      - sensor.kalavalanas_drive_temp
      - sensor.kalavalanas_system_temperature
      - sensor.kalavalanas_cpu_temperature

  QNAP Automations:
    entities:
      - automaton.notify_nas_drive_status_change
      - automaton.notify_nas_status_change
      - automation.notify_nas_memory_usage
      - automation.notify_nas_disk_usage
      - automation.notify_nas_cpu_usage
      - automation.notify_nas_cpu_temperature

sensor:
  - platform: qnap
    host: !secret qnap_hostname
    username: !secret qnap_username
    password: !secret qnap_password
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - volume_percentage_used
      - system_temp
      - cpu_temp
      - drive_smart_status
      - drive_temp

# The following sensors are required, as the automations with trigger platform `numeric_state`, 
# above a certain value using `above: x` AND `for: 00:05:00` combination is not supported.
#
# Apparently `for:` is ONLY supportd for trigger platform 'state' 
#
# By creating the folowing sensor, we can now have an automation with trigger platform as 'state'
# with a combination of `to:` and `for:`
#
# See the automations 'Notify NAS Memory Usage' and 'Notify NAS CPU Usage' that uses these sensor values

  - platform: template
    sensors:
      nas_memory_usage_above_80:
        value_template: '{{ states.sensor.kalavalanas_memory_usage.state | int > 80 }}'

  - platform: template
    sensors:
      nas_cpu_usage_above_80:
        value_template: '{{ states.sensor.kalavalanas_cpu_usage.state | int > 80 }}'

automation:

  - alias: Notify NAS Status Change
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: 
       - sensor.kalavalanas_status
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    action:
      - service: script.notify_me
        data_template:
          message: "NAS Status changed to: {{ trigger.to_state.state| upper }}"

  - alias: Notify NAS Drive Status Change
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: 
       - sensor.kalavalanas_smart_status_drive_01
       - sensor.kalavalanas_smart_status_drive_02
       - sensor.kalavalanas_smart_status_drive_03
       - sensor.kalavalanas_smart_status_drive_04
    condition:
      - condition: template
        value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"       
    action:
      - service: script.notify_me
        data_template:
          message: "NAS Drive state changed to: 
          {{ trigger.to_state.state| upper }} from 
          '{{ trigger.from_state.state| upper }}'"

  - alias: Notify NAS CPU Temperature
    initial_state: true
    hide_entity: true
    trigger:
      platform: numeric_state
      entity_id:  sensor.kalavalanas_cpu_temperature
      above: 125
    action:
      - service: script.notify_me
        data_template:
          message: "NAS CPU temperature is going crazy hot, needs your attention!!! 
          The current cpu temp is: {{ trigger.to_state.state }}"

  - alias: Notify NAS Disk Usage
    initial_state: true
    hide_entity: true
    trigger:
      platform: numeric_state
      entity_id:  sensor.kalavalanas_volume_used_datavol1
      above: 80
    action:
      - service: script.notify_me
        data_template:
          message: "Attention! NAS disk usage is above 80 percent. Time to clean up?"

  - alias: Notify NAS Memory Usage
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: sensor.nas_memory_usage_above_80
      to: 'True'
      for: '00:05:00'
    action:
      - service: script.notify_me
        data_template:
          message: "FYI - NAS Memory is above 80 percent for more than 5 minutes."

  - alias: Notify NAS CPU Usage
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id:  sensor.nas_cpu_usage_above_80
      to: 'True'
      for: '00:05:00'
    action:
      - service: script.notify_me
        data_template:
          message: "FYI - NAS CPU is above 80 percent for more than 5 minutes."
