homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'settings'

      exposed: &exposed
        <<: *customize
        emulated_hue_hidden: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue_hidden: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    group.control_panel:
      <<: *not_exposed

    input_boolean.working_in_garage:
      <<: *exposed
      friendly_name: Working in Garage
      icon: mdi:worker
    input_boolean.working_in_office_room:
      <<: *exposed
      friendly_name: Working in Office Room
      icon: mdi:worker
    input_boolean.voice_notifications:
      <<: *exposed
      icon: mdi:microphone-off
      emulated_hue_name: Home Assistant Announcements
      homebridge_name: Home Assistant Announcements
    input_boolean.do_not_disturb:
      <<: *exposed
      homebridge_name: Do Not Disturb
    input_boolean.home_security:
      <<: *exposed
      homebridge_name: Turn ON Home Security
    input_boolean.home_assistant_restart:
      <<: *exposed
      homebridge_name: Restart Home Assistant
    input_boolean.home_assistant_status:
      <<: *exposed
      homebridge_name: Home Status
    input_boolean.alarm_clock:
      <<: *exposed
      homebridge_name: Alarm Clock
    input_boolean.sharp_tv:
      <<: *exposed
      homebridge_name: TV

    input_datetime.summer_bed_time:
      icon: mdi:beach
    input_datetime.summer_wakeup_time:
      icon: mdi:beach
      
    input_datetime.autumn_bed_time:
      icon: mdi:leaf
    input_datetime.autumn_wakeup_time:
      icon: mdi:leaf

    input_datetime.winter_bed_time:
      icon: mdi:snowflake
    input_datetime.winter_wakeup_time:
      icon: mdi:snowflake

    input_datetime.spring_bed_time:
      icon: mdi:tree
    input_datetime.spring_wakeup_time:
      icon: mdi:tree

    sensor.wakeup_hour:
      <<: *hidden
    sensor.wakeup_minute:
      <<: *hidden
    sensor.bedtime_hour:
      <<: *hidden
    sensor.bedtime_minute:
      <<: *hidden

group:
  Control Panel:
    control: hidden
    entities:
      - input_boolean.voice_notifications
      - input_boolean.do_not_disturb
      - input_boolean.home_security
      - input_boolean.home_assistant_restart
      - input_boolean.home_assistant_update
      - input_boolean.home_assistant_status
      - input_boolean.notify_motion_pictures
      - input_boolean.working_in_garage
      - input_boolean.working_in_office_room
      - input_boolean.hourly_reports
      - input_boolean.welcome_family_announcement
      - input_boolean.trash_reminders
      - input_boolean.enjoyable_weather_reminders
      - input_boolean.alert_when_someone_enters_zone
      - input_boolean.alert_when_someone_leaves_zone
      - input_boolean.alarm_clock
      - input_boolean.notify_security_system_changes
      - input_boolean.air_condition
      - input_boolean.heater
      - input_boolean.alert_no_one_home
      - input_boolean.battery_notifications
      - input_number.calendar_remind_before_days
      - input_boolean.wfh_notifications
      - input_boolean.sharp_tv

  Bed & Wakeup Times:
    entities:
      - input_datetime.summer_bed_time
      - input_datetime.summer_wakeup_time
      - input_datetime.autumn_bed_time
      - input_datetime.autumn_wakeup_time
      - input_datetime.winter_bed_time
      - input_datetime.winter_wakeup_time
      - input_datetime.spring_bed_time
      - input_datetime.spring_wakeup_time

# Input DateTime Options:
# I set the minutes to something that is divisible by 5, so that the automations
# can check once every 5 minutes without any performance penalty 
###############################################################################

input_datetime:
  summer_bed_time:
    name: Summer Bed Time
    has_date: false
    has_time: true
    initial: '23:00:00'
  summer_wakeup_time:
    name: Summer Wakeup Time
    has_date: false
    has_time: true
    initial: '06:00:00'

  autumn_bed_time:
    name: Autumn Bed Time
    has_date: false
    has_time: true
    initial: '22:00:00'
  autumn_wakeup_time:
    name: Autumn Wakeup Time
    has_date: false
    has_time: true
    initial: '05:30:00'

  winter_bed_time:
    name: Winter Bed Time
    has_date: false
    has_time: true
    initial: '22:00:00'
  winter_wakeup_time:
    name: Winter Wakeup Time
    has_date: false
    has_time: true
    initial: '05:30:00'

  spring_bed_time:
    name: Spring Bed Time
    has_date: false
    has_time: true
    initial: '22:00:00'
  spring_wakeup_time:
    name: Spring Wakeup Time
    has_date: false
    has_time: true
    initial: '05:30:00'

input_number:
  calendar_remind_before_days:
    name: Calendar Remind Before Days
    initial: 2
    min: 1
    max: 15
    step: 1

sensor:
  - platform: template
    sensors:
      wakeup_hour:
        friendly_name: Wakeup Hour
        value_template: >
          {% if states.sensor.season.state | lower == "summer" %}
            {{ states.input_datetime.summer_wakeup_time.state.split(':')[0] }}
          {% elif states.sensor.season.state | lower == "autumn" %}
            {{ states.input_datetime.autumn_wakeup_time.state.split(':')[0] }}
          {% elif states.sensor.season.state | lower == "winter" %}
            {{ states.input_datetime.winter_wakeup_time.state.split(':')[0] }}
          {% elif states.sensor.season.state | lower == "spring" %}
            {{ states.input_datetime.spring_wakeup_time.state.split(':')[0] }}
          {% else %}
            6
          {% endif %}
      wakeup_minute:
        friendly_name: Wakeup Minute
        value_template: >
          {% if states.sensor.season.state | lower == "summer" %}
            {{ states.input_datetime.summer_wakeup_time.state.split(':')[1] }}
          {% elif states.sensor.season.state | lower == "autumn" %}
            {{ states.input_datetime.autumn_wakeup_time.state.split(':')[1] }}
          {% elif states.sensor.season.state | lower == "winter" %}
            {{ states.input_datetime.winter_wakeup_time.state.split(':')[1] }}
          {% elif states.sensor.season.state | lower == "spring" %}
            {{ states.input_datetime.spring_wakeup_time.state.split(':')[1] }}
          {% else %}
            0
          {% endif %}
      bedtime_hour:
        friendly_name: Bedtime Hour
        value_template: >
          {% if states.sensor.season.state | lower == "summer" %}
            {{ states.input_datetime.summer_bed_time.state.split(':')[0] }}
          {% elif states.sensor.season.state | lower == "autumn" %}
            {{ states.input_datetime.autumn_bed_time.state.split(':')[0] }}
          {% elif states.sensor.season.state | lower == "winter" %}
            {{ states.input_datetime.winter_bed_time.state.split(':')[0] }}
          {% elif states.sensor.season.state | lower == "spring" %}
            {{ states.input_datetime.spring_bed_time.state.split(':')[0] }}
          {% else %}
            0
          {% endif %}
      bedtime_minute:
        friendly_name: Bedtime Minute
        value_template: >
          {% if states.sensor.season.state | lower == "summer" %}
            {{ states.input_datetime.summer_bed_time.state.split(':')[1] }}
          {% elif states.sensor.season.state | lower == "autumn" %}
            {{ states.input_datetime.autumn_bed_time.state.split(':')[1] }}
          {% elif states.sensor.season.state | lower == "winter" %}
            {{ states.input_datetime.winter_bed_time.state.split(':')[1] }}
          {% elif states.sensor.season.state | lower == "spring" %}
            {{ states.input_datetime.spring_bed_time.state.split(':')[1] }}
          {% else %}
            0
          {% endif %}

# Input Booleans Options
###############################################################################

input_boolean:
  voice_notifications:
    name: Home Assistant Announcements
    initial: on
    icon: mdi:volume-off

  do_not_disturb:
    name: Do Not Disturb
    initial: off
    icon: mdi:do-not-disturb

  home_security:
    name: Home Security System
    initial: off
    icon: mdi:verified

  home_assistant_restart:
    name: Home Assistant
    initial: off
    icon: mdi:home-assistant

  home_assistant_update:
    name: Latest Version Of Home Assistant
    initial: off
    icon: mdi:home-assistant

  home_assistant_status:
    name: Home Status
    initial: off
    icon: mdi:home-assistant

  working_in_garage:
    name: Working in Garage
    initial: off
    icon: mdi:worker

  working_in_office_room:
    name: Working in Office Room
    initial: off
    icon: mdi:worker

  hourly_reports:
    name: Hourly Report
    initial: on
    icon: mdi:file-chart

  notify_motion_pictures:
    name: Notify With Pictures (Motion)
    initial: off
    icon: mdi:camera

  welcome_family_announcement:
    name: Welcome Family Member Announcements
    initial: on
    icon: mdi:home

  trash_reminders:
    name: Remind Trash Notifications
    initial: on
    icon: mdi:recycle

  enjoyable_weather_reminders:
    name: Remind me to enjoy Good Weather
    initial: on
    icon: mdi:weather-sunny

  notify_security_system_changes:
    name: Notify Security System Status Change
    initial: on
    icon: mdi:verified

  alert_no_one_home:
    name: Alert When No One Home
    initial: on
    icon: mdi:alert

  alert_when_someone_enters_zone:
    name: Alert When Someone Enters A Zone
    initial: on
    icon: mdi:map-marker

  alert_when_someone_leaves_zone:
    name: Alert When Someone Leaves A Zone
    initial: on
    icon: mdi:map-marker

  alarm_clock:
    name: Alarm Clock
    initial: on
    icon: mdi:calendar-check

  battery_notifications:
    name: Battery Notifications
    initial: on
    icon: mdi:battery

  wfh_notifications:
    name: Work From Home
    initial: off
    icon: mdi:work

  sharp_tv:
    name: TV
    initial: on
    icon: mdi:television-classic

# Automations
###############################################################################

automation:

# Do not disturb for 2 hours
# Simply turns ON the Do Not Disturb Flag ad resets 
# after 2 hours. The Do Not Disturb flag is used in
# voice_notify script
######################################################
  - alias: Do Not Disturb For 2 hours
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.do_not_disturb
        to: 'on'
        for:
          hours: 2
          minutes: 0
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.do_not_disturb

# Turn ON Home Security System - only if it is not ON
######################################################
  - alias: Home Security ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_security
        to: 'on'
    condition:
      - condition: template
        value_template: '{{ states.alarm_control_panel.simplisafe.state == "disarmed" }}'
    action:
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.simplisafe
      - delay:
          minutes: 0
          seconds: 10
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_security

# Announces "Status" in the house
######################################################
  - alias: Home Status ON
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_status
        to: 'on'
    action:
      - service: script.home_status
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_assistant_status

# Restarts Home Assistant at Alexa's Command
######################################################
  - alias: Restart Home Assistant
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_restart
        to: 'on'
    action:
      - service: script.restart_hass
        
# Updates Home Assistant at Alexa's Command
######################################################
  - alias: Update Home Assistant
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_boolean.home_assistant_update
        to: 'on'
    action:
      - service: script.update_hass
      - delay:
          minutes: 0
          seconds: 10
      - service: input_boolean.turn_off
        entity_id: input_boolean.home_assistant_update

# Hourly Reports
######################################################
  - alias: Hourly Report During Day Time
    initial_state: true
    hide_entity: true
    trigger:
      platform: time
      hours: '/01'
      minutes: 05
      seconds: 00
    condition:
      - condition: template
        value_template: '{{ states.input_boolean.hourly_reports.state == "on" }}'
      - condition: state
        entity_id: group.all_devices
        state: 'home'
      - condition: template
        value_template: >
          {% set hour = now().hour | int %}
          {% if  hour > 7 and hour < 21 %}
            true
          {% else %}
            false
          {% endif %}
    action:
      - service: script.home_status
