homeassistant:

  ################################################################################
  ## CUSTOMIZE
  ################################################################################

  customize:

    ################################################################################
    ## NODE ANCHORS
    ################################################################################

    package.node_anchors:
      customize: &customize
        package: 'traffic'

      hidden: &hidden
        <<: *customize
        hidden: true
        emulated_hue_hidden: true

################################################################################
## CAMERAS
################################################################################

camera:
#**************************** Traffic Gary CAM **********************************
  - platform: generic
    name: Traffic Cam 69 S IN67
    still_image_url: http://pws.trafficwise.org/pullover/172_21_21_24.jpg
  - platform: generic
    name: Traffic Cam 69 N of SR38
    still_image_url: http://pws.trafficwise.org/pullover/172_21_21_220.jpg
  - platform: generic
    name: Traffic Cam 69/218.8 SR38
    still_image_url: http://pws.trafficwise.org/pullover/172_21_21_87.jpg
  - platform: generic
    name: Traffic Cam 69/217.6 S of SR38
    still_image_url: http://pws.trafficwise.org/pullover/172_21_21_74.jpg
  - platform: generic
    name: Traffic Cam 69 SR13
    still_image_url: http://pws.trafficwise.org/pullover/172_21_21_41.jpg
  - platform: generic
    name: Traffic Cam 69/212.3 Cyntheanne RD
    still_image_url: http://pws.trafficwise.org/pullover/172_21_21_11.jpg
  - platform: generic
    name: Traffic Cam 69/210.2 Campus PKWY
    still_image_url: http://pws.trafficwise.org/pullover/172_20_21_84.jpg
#**************************** Traffic CAM **********************************
  - platform: generic
    name: Traffic Cam 69/205.5 SR 37
    still_image_url: http://pws.trafficwise.org/pullover/172_20_21_55.jpg
  - platform: generic
    name: Traffic Cam 69/205 116Th ST
    still_image_url: http://pws.trafficwise.org/pullover/172_20_21_50.jpg
  - platform: generic
    name: Traffic Cam 69/202.7 96TH ST
    still_image_url: http://pws.trafficwise.org/pullover/172_20_21_27.jpg
  - platform: generic
    name: Traffic Cam 69/200.9 82ND ST
    still_image_url: http://pws.trafficwise.org/pullover/172_20_21_9.jpg
  - platform: generic
    name: 69/200.2 I-465 Ramps W.
    still_image_url: http://pws.trafficwise.org/pullover/172_20_21_22.jpg