homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'tts'

      exposed: &exposed
        <<: *customize
        emulated_hue_hidden: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue_hidden: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

      not_hidden: &not_hidden
        <<: *customize
        hidden: false
        critical: true

    input_text.tts:
      <<: *not_hidden
      icon: mdi:speaker
    input_boolean.greeting:
      <<: *not_exposed

    group.text_to_speech:
      name: TTS
      <<: *not_hidden

group:
  Text To Speech:
    entities:
      - input_text.tts
      - input_boolean.greeting

input_text:
  tts:
    name: Text To Speech
    initial: Initial text

input_boolean:
  greeting:
    name: Greeting
    initial: off

automation:

###############################################################################
# The text entered in the text box will be announced in the house
###############################################################################
  - alias: Text Changed Event
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_text.tts
    action:
      - service: script.voice_notify
        data_template:
          message: "{{ trigger.to_state.state }}"
          greeting: "{{ 'yes' if states.input_boolean.greeting.state == 'on' else 'no' }}"