###############################################################################
#   @author         :   Trent Stanton
#   @date           :   10/03/2018
#   @package        :   UPS
#   @description    :   
#   @url            :   
###############################################################################
homeassistant:
  customize:
    sensor.ups_status:
      icon: mdi:information-outline
    sensor.ups_battery_runtime_mins:
      icon: mdi:timer

group:
  ups:
    name: "UPS"
    control: hidden
    entities:
      - sensor.ups_status
      - sensor.ups_load
      - sensor.ups_battery_runtime_mins
      - sensor.ups_battery_charge

sensor:
# Translate UPS Status / Runtime
  - platform: template
    sensors:
      ups_status:
        friendly_name: 'UPS Status'
        value_template: >-
          {% if is_state('sensor.ups_status_data', 'OL CHRG') %}
            On line Charging
          {% elif is_state('sensor.ups_status_data', 'OB DISCHRG') %}
            On Battery
          {% elif 'LB' in states.sensor.ups_status_data.state %}
             Low battery
          {% elif 'OL' in states.sensor.ups_status_data.state %}
             On line
          {% elif 'SD' in states.sensor.ups_status_data.state %}
            Shutdown load
          {% elif 'CP' in states.sensor.ups_status_data.state %}
            Cable power
          {% elif 'CTS' in states.sensor.ups_status_data.state %}
            Clear to Send
          {% elif 'RTS' in states.sensor.ups_status_data.state %}
            Ready to Send
          {% elif 'DCD' in states.sensor.ups_status_data.state %}
            Data Carrier Detect
          {% elif 'RNG' in states.sensor.ups_status_data.state %}
            Ring indicate
          {% elif 'DTR' in states.sensor.ups_status_data.state %}
            Data Terminal Ready
          {% elif 'ST' in states.sensor.ups_status_data.state %}
            Send Break
          {% endif %}
      ups_battery_runtime_mins:
        friendly_name: 'UPS Battery Runtime'
        unit_of_measurement: 'minutes'
        value_template: "{{ states('sensor.ups_battery_runtime')|float / 60 |round(2)}}" 
# Synology UPS Data
  - platform: nut
    name: UPS
    host: !secret sensor_synology_host
    port: 3493
    alias: UPS
    resources:
      - ups.status
      - ups.load
      - ups.realpower.nominal
      - input.voltage
      - battery.runtime
      - battery.charge

###############################################################################
#                               Automations
###############################################################################
automation:
  - alias: 'Send notification when UPS is on battery'
    trigger:
    - platform: state
      entity_id: sensor.ups_status_data
      to: 'OB DISCHRG'
    action:
    - service: notify.trent
      data:
        message: "Power Alert! The UPS has switched to Battery Power."
        
  - alias: 'Send notification when UPS is low battery'
    trigger:
    - platform: state
      entity_id: sensor.ups_status_data
      to: 'LB'
    action:
    - service: notify.trent
      data:
        message: "Power Alert! The UPS has got Low Power."
  
  - alias: 'Send notification when UPS is back on line'
    trigger:
    - platform: state
      entity_id: sensor.ups_status_data
      to: 'OL CHRG'
    action:
    - service: notify.trent
      data:
        message: "Power Alert! The UPS is back On line."