homeassistant:
  customize:

    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'xiaomi'

      exposed: &exposed
        <<: *customize
        emulated_hue_hidden: true
        homebridge_hidden: false
        critical: true

      not_exposed: &not_exposed
        <<: *customize
        emulated_hue_hidden: false
        homebridge_hidden: true
        critical: false

      hidden: &hidden
        <<: *customize
        hidden: true
        critical: false

    binary_sensor.motion_sensor_158d0001a662fe:
      friendly_name: Kitchen Motion Sensor
    sensor.Illumination_158d0001a662fe:
      friendly_name: Kitchen Luminance
     
    binary_sensor.motion_sensor_158d0001a25041:
      friendly_name: Family Room Motion Sensor (xiaomi)
    sensor.Illumination_158d0001a25041:
      friendly_name: Family Room Luminance (xiaomi)
 
    binary_sensor.motion_sensor_158d00016db6d2:
      friendly_name: Front Room Motion Sensor
    sensor.Illumination_158d00016db6d2:
      friendly_name: Front Room Luminance
    
    binary_sensor.motion_sensor_158d00016c2d0e:
      friendly_name: Dining Room Motion Sensor
    sensor.Illumination_158d00016c2d0e:
      friendly_name: Dining Room Luminance

    sensor.Illumination_34ce008ad65d:
      friendly_name: Hallway Luminance

    light.gateway_light_34ce008ad65d:
      friendly_name: Xiaomi Aqara Gateway Light

group:
  Xiaomi Aqara:
    entities:
      - binary_sensor.motion_sensor_158d0001a662fe
      - binary_sensor.motion_sensor_158d0001a25041
      - binary_sensor.motion_sensor_158d00016db6d2
      - binary_sensor.motion_sensor_158d00016c2d0e
      - sensor.Illumination_158d0001a662fe
      - sensor.Illumination_158d0001a25041
      - sensor.Illumination_158d00016db6d2
      - sensor.Illumination_158d00016c2d0e
      - sensor.Illumination_34ce008ad65d

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_key