input_text:
  youtube_url:
    name: YouTube URL
    initial: 'https://www.youtube.com/watch?v=alm844msx6E'

automation:
  - alias: Stream URL Text Changed Event
    initial_state: true
    hide_entity: true
    trigger:
      - platform: state
        entity_id: input_text.youtube_url
    action:
      - service: media_extractor.play_media
        data_template:
          entity_id: media_player.gstreamer
          media_content_id: "{{states.input_text.youtube_url.state}}"
          media_content_type: 'video/mp4'